Update .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -9,6 +9,17 @@ language: objective-c
 # before_install:
 # - gem install cocoapods # Since Travis is not always on latest version
 # - pod install --project-directory=Example
+install:
+# if setuptools<17.1 installing even dependencies could fail
+#- if [ "$TRAVIS_OS_NAME" == "osx" ]; then travis_retry wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;bash miniconda.sh -b -p $HOME/miniconda; export PATH="$HOME/miniconda/bin:$PATH" ;  fi
+- |
+  set -e
+  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
+    rvm get stable
+    which python || travis_retry brew install python && brew link --overwrite python
+    which python
+    python --version
+  fi
 script:
 - set -o pipefail && xcodebuild test -workspace Example/MRCountryPicker.xcworkspace -scheme MRCountryPicker-Example -sdk iphonesimulator10.0 ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' | xcpretty
-# - pod lib lint
+- pod lib lint
